package com.springdemo.blog.po;
import java.util.Date;

/**
 * Articleclickrate generated by hbm2java
 */
public class Articleclickrate implements java.io.Serializable {

	private int id;
	private Integer articleid;
	private String ip;
	private Date time;

	public Articleclickrate() {
	}

	public Articleclickrate(int id) {
		this.id = id;
	}

	public Articleclickrate(int id, Integer articleid, String ip, Date time) {
		this.id = id;
		this.articleid = articleid;
		this.ip = ip;
		this.time = time;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getArticleid() {
		return this.articleid;
	}

	public void setArticleid(Integer articleid) {
		this.articleid = articleid;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
