package com.springdemo.blog.po;
// Generated 2017-5-31 22:29:41 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * Article generated by hbm2java
 */
public class Article implements java.io.Serializable {

	@Override
	public String toString() {
		return "Article [id=" + id + ", title=" + title + ", content=" + content + ", username=" + username + ", date="
				+ date + ", hasread=" + hasread + ", flag=" + flag + ", type=" + type + "]";
	}

	private int id;
	private String title;
	private String content;
	private String username;
	private Date date;
	private Integer hasread;
	private int flag;
	private Integer type;

	public Article() {
	}

	public Article(int id, int flag) {
		this.id = id;
		this.flag = flag;
	}

	public Article(int id, String title, String content, String username, Date date, Integer hasread, int flag,
			Integer type) {
		this.id = id;
		this.title = title;
		this.content = content;
		this.username = username;
		this.date = date;
		this.hasread = hasread;
		this.flag = flag;
		this.type = type;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Integer getHasread() {
		return this.hasread;
	}

	public void setHasread(Integer hasread) {
		this.hasread = hasread;
	}

	public int getFlag() {
		return this.flag;
	}

	public void setFlag(int flag) {
		this.flag = flag;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

}
