package com.springdemo.blog.po;
// Generated 2017-5-31 22:29:41 by Hibernate Tools 5.2.0.Beta1

/**
 * Articonmen generated by hbm2java
 */
public class Articonmen implements java.io.Serializable {

	private int id;
	private Integer aritcleid;
	private String content;
	private String username;

	public Articonmen() {
	}

	public Articonmen(int id) {
		this.id = id;
	}

	public Articonmen(int id, Integer aritcleid, String content, String username) {
		this.id = id;
		this.aritcleid = aritcleid;
		this.content = content;
		this.username = username;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getAritcleid() {
		return this.aritcleid;
	}

	public void setAritcleid(Integer aritcleid) {
		this.aritcleid = aritcleid;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
