package com.springdemo.blog.po;
// Generated 2017-5-31 22:29:41 by Hibernate Tools 5.2.0.Beta1

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	
	private String username;
	private String pwd;
	private String nickname;
	private String question;
	private String answer;
	
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPwd() {
		return pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getNickname() {
		return nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getQuestion() {
		return question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getAnswer() {
		return answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	
	@Override
	public String toString() {
		return "User [username=" + username + ", pwd=" + pwd + ", nickname=" + nickname + ", question=" + question
				+ ", answer=" + answer + "]";
	}

	
}
